### ISSUE TITLE
Max message size rejects messages and closes connection

### ISSUE THREAD

**Issue by sampie777** [Twasi/websocket-obs-java#11]
In OBSCommunicator.java the maxTextMessageSize is set to 64 kB. When OBS has too much scenes/sources that a call for GetSceneList returns a message with a size greater than 64 kB. This lets the websocket client collapse: connection is lost (without an error) and my application tries to reconnect, which will result in a circular loop. Increasing maxTextMessageSize will prevent this problem.

My question is: is this possible? I don't know the reason why 64 kB was chosen in the first place. Can this be raised, to lets say 200 kB (to be save)? Or maybe this can be made configurable by the client using this client? 

For your reference, according to my calculations too much scenes/sources are something like: 34 scenes with each 4 sources, or 17 scenes with each 8 sources, ...

**Comment by LarsBaertschi** [comment]
We have discussed this today, and came to the conclusion that setting a maximum is not required. We have no idea why we did this when we implemented it.
We have removed it, and plan it to release it along the next release we do. https://github.com/Twasi/websocket-obs-java/commit/c62490999b9b1ffe6f906deab14d6b83a8ea68b7

**Comment by sampie777** [comment]
Thank you for your reply. By removing it, do you know what will be the default max size?

**Comment by LarsBaertschi** [comment]
When removing the limit, there is no limit set. Web socket supports multi-frame transmission, which means that packages / messages can theoretically be as big as they like without any limitations. However, when the messages get very big, you may see the performance degrade, especially trough our parsing process. However, this should not be any problem when only talking about some kB...

**Comment by sampie777** [comment]
Thank you for the explanation. It's strange that the default WebSocket behavior is to close the connection when a message to big arrives, instead of just throwing an error.
Thanks for the fix!
