### ISSUE TITLE
Usage: stale connections / Android?

### ISSUE THREAD

**Issue by yourealwaysbe** [Twasi/websocket-obs-java#12]
Thanks for your work on this.

I'm trying to use it to implement a basic Android remote control, however i get some odd behaviour.

When i create an app, i open up a connection. If i use it immediately to change scene, it is fine. If i make the change scene request later in a button click handler, it never seems to go through. However, it does work if i create a fresh connection object in the click handler.

In addition, i can add a switch scene callback when creating the app, and this seems to stay active throughout. It receives scene changes triggered directly in OBS, even though the setCurrentScene in the click handler, using the same connection object, never reaches OBS.

Is there a subtlety to using the library that i haven't understood, or should i put it down to Android screwiness?

Code attached for reference:
[MainActivity.kt](https://github.com/Twasi/websocket-obs-java/files/4981448/MainActivity.txt)

**Comment by yourealwaysbe** [comment]
Sorry, closing this, on reflection it's probably to do with not using the same connection in multiple threads.

**Comment by LarsBaertschi** [comment]
Yes, exactly! You should create a single thread that interacts with our library. Maybe it would make sense for our library to implement a scheduler and a pipe so that you could send requests from whatever thread you want, and the wrapper would take care to schedule it to the correct thread. But that's something for the future.

**Comment by yourealwaysbe** [comment]
Thanks for the response. I should have replied earlier -- i read somewhere that in recent versions of Android, HTTP connections are blocked on the UI thread (rather than this just being bad practice). When using this library only in Dispatchers.IO coroutines in Kotlin, things works fine.
