### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by gxalpha** [Twasi/websocket-obs-java#14]
This library doesn't include an obvious license, technically making it unusable in any program without the permission of every contributor.
I did see it included in the pom.xml, but I personally think you should add a LICENSE document and/or headers to the specific document to make it more clear.
*Note that this is not legal advise, and I'm not a lawyer :)*

**Comment by LarsBaertschi** [comment]
Hey!

Good catch, how did we miss this all the time? All our open-source projects are licensed under MIT, so this one should be too. I have checked back with all contributors. As you correctly saw in pom.xml we intended to have the project MIT-licensed all the time.

We have added the MIT License file also to the root path of the directory (as it is done normally) so we have it more obvious and explicitly stated.

Again thank you very much! If you have any more questions or concerns feel free to reopen or comment.

Best regards,
Lars
