### ISSUE TITLE
There appears to be no getSourcesList function

### ISSUE THREAD

**Issue by FabianKopp** [Twasi/websocket-obs-java#16]
There appears to be no getSourcesList function.
There is one within a scene object, but no function to list all sources in OBS

**Comment by DieserMerlin** [comment]
Feel free to make a PR

**Comment by LarsBaertschi** [comment]
You can use getSceneList and go from there over all available sources for now.

**Comment by TinaTiel** [comment]
protocol: https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsourceslist

**Comment by ChristopheCVB** [comment]
This can be closed, resolved by #37

**Comment by ChristopheCVB** [comment]
@TinaTiel Can you close this please?

**Comment by TinaTiel** [comment]
Sure, thanks for reminding me :)
