### ISSUE TITLE
Can't make Source (in)visible

### ISSUE THREAD

**Issue by Janisbtw** [Twasi/websocket-obs-java#2]
I tried to make a source invisible but nothing happens. I tested it with following code:
Map<String, Object> m = new HashMap<>();
m.put("visible", "false");
controller.setSourceSettings("Bildschirmaufnahme", m, res -> {

});
Btw, if it's possible can you add a method to check if something is muted and start/stop recording?
Is it possible to make a source (in)visible while not on Scene where the source is added

**Comment by LarsBaertschi** [comment]
Library seems to work as expected. Settings object is serialized and passed to obs-websocket, so you maybe need to check if there is an issue there hindering you hiding the scene.
