### ISSUE TITLE
GPG Prompt During Verify Phase (GPG V 2.1+) [Fix on TinaTiel Fork]

### ISSUE THREAD

**Issue by TinaTiel** [Twasi/websocket-obs-java#20]
While running the Maven verify phase to sign the jar, a GPG prompt appears. 
This only occurs in GPG V 2.1+ and a fixed is described here:

https://myshittycode.com/2017/08/07/maven-gpg-plugin-prevent-signing-prompt-or-gpg-signing-failed-no-such-file-or-directory-error/

Fix is simple as specifying the `pinentry-mode` as `loopback` in the GPG properties:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <version>1.6</version>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
            <configuration>
                <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                </gpgArguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I've already fixed it here: 
https://github.com/TinaTiel/websocket-obs-java/issues/8

Not sure if you're going to want to bother with a topic branch for this, I didn't on my fork.
I also added brief docs in the README about the build process so folks that haven't signed jars before understand how to setup maven properties in their IDE for example.

**Comment by DieserMerlin** [comment]
Thank you! I'm closing this as it has been merged.
