### ISSUE TITLE
Suggestion: SLOBS Protocol Support

### ISSUE THREAD

**Issue by TinaTiel** [Twasi/websocket-obs-java#23]
Was following a [thread on Twitter](https://twitter.com/TinaTiel/status/1345888648617734144?s=20) and through that conversation realized some folks are using SLOBS. 

I took a look at their protocol, and they do natively support websockets but their protocol/objects are different: 
https://stream-labs.github.io/streamlabs-obs-api-docs/docs/index.html

Googled around and didn't find any usage stats, but there were a few loud folks recommending SLOBS. 
For relevancy, might be good to offer a client that supports SLOBS protocol too.

**Comment by rnayabed** [comment]
+1 SLOBS Protocol Support would be awesome!

**Comment by DieserMerlin** [comment]
None of us work with SLOBS, so there are no plans to integrate that now or in the future. We would still be happy if you would take a look at it and make a pull request for integration!

**Comment by TinaTiel** [comment]
Cool, sounds good! 
I intend to eventually work this, I just put it in here as a placeholder in case others were thinking the same thing.

**Comment by TinaTiel** [comment]
Btw @DieserMerlin I think it would be several steps. 

Would be a lot of work, so would your preference be to (a) put it all in one branch, or (b) make PRs for each step? My personal style has been to create an Issue/PR for each unit of work, but this ain't my repo haha

**Comment by DieserMerlin** [comment]
You got write permission on the repository. How you do it is up to you, just try not to break anything 😅 

Welcome to the team 😎
Also please have a look at the issues related to SLOBS. I created a label for it.

**Comment by DieserMerlin** [comment]
Also please take a look at my most recent commit introducing generics to get away from this cast-mess. Would be greate to have a consistent code style for both, "normal" and streamlabs-obs.

**Comment by TinaTiel** [comment]
Sure, will take a look...

**Comment by TinaTiel** [comment]
SO far only seeing one issue for SLOBS -- when I get to it, there WILL be more 😉

**Comment by rnayabed** [comment]
Im incorporating this in a very huge project, thanks a lot for this 🥇

**Comment by Pezcraft** [comment]
Are you still working on it?

**Comment by TinaTiel** [comment]
Hi! Not at the moment, sorry!
I've had to prioritize other things, I'll unassign myself for now -- sorry for confusion!

**Comment by TinaTiel** [comment]
Hi! Not at the moment, sorry!
I've had to prioritize other things, I'll unassign myself for now -- sorry for confusion!

**Comment by ChristopheCVB** [comment]
I think that SLOBS should not be integrated in this library, but be an entirely different one. OBS WebSocket and SLOBS Protocols are differents.

**Comment by TinaTiel** [comment]
@ChristopheCVB We could generify the library quite a bit, it would be part of a larger effort. 
The protocols are different, but it doesn't mean we couldn't accomplish it here (bigger would be if the functionalities were completely different, e.g. feature parity between SLOBS and OBS Studio). 

As I imagine it in my head, it might phase in like this:

1. Switch to a generic client interface and implementation
```
public interface ObsClient {
	// Lifecycle controls
	void connect();
	void disconnect();
	// and so on
}
public class ObsStudioClient implements ObsClient {...}
```
2. Update with listener-based structures, to improve testability
```
public interface ObsClient {
	// Lifecycle controls
	void connect();
	void disconnect();
	void registerLifecycleListener(LifecycleListener listener);
	void registerObsEventListener(ObsEventListener listener);
	ObsController getController();
}
public interface LifecycleListener {
	void onConnect(ConnectEvent event);
	void onConnectFailure(ConnectFailureEvent event);
	void onAuthenticate(AuthenticateEvent event); // we'll have to see about this one
	void onAuthenticateFailureEvent(OnAuthenticateFailureEvent event); // we'll have to see about this one
	void onErrorEvent(ErrorEvent event);
}
public interface ObsEventListener {
	void onSceneChanged(SceneChangedEvent event);
	void onSourceFilterVisibilityChanged(SourceFilterVisibilityChangedEvent event);
	// And so-forth
}
public ObsController {
	void changeScene(String scene, ChangeSceneCallback callback);
	// and so forth
}
```
Listeners would be really important for testability, so you can e.g. better unit and integration test lifecycle events etc. without needing to startup a real connection. And ofc adding your own would be optional as there would be a default lifecycle listener for example. 
3. Add an Slobs implementation
```
public class ObsStudioClient implements ObsClient {...}
public class SlobsClient implements ObsClient {...}
```
Ideally, it would be good to introduce builders as well:
```
ObsStudioClient obsStudioClient = ObsStudioClient.builder()
	.host("localhost")
	.port(4444)
	.lifecycleListener(...)
	.obsListener(...)
	.build();

SlobsStudioClient obsStudioClient = SlobsClient.builder()
	.host("localhost")
	.port(4444)
	.lifecycleListener(...)
	.obsListner(...)
	.build();
```
These are of course just ideas! Not planning to work on them yet, but if you have feedback on this it is ofc welcome!
Inspiration is the PircBotX IRC client, if you want to get a better idea of how that'd work.

**Comment by TinaTiel** [comment]
For now, given the big changes with the OBS Studio plugin and this library as-is, there aren't plans to work on this.
