### ISSUE TITLE
Feature request: toggle filter visibility

### ISSUE THREAD

**Issue by jonteohr** [Twasi/websocket-obs-java#25]
Would be nice to be able to toggle filter visibility of a source/scene.
Is this something that's planned?

**Comment by TinaTiel** [comment]
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setsourcefiltervisibility

Don't see why not

**Comment by TinaTiel** [comment]
I'll go ahead and just do this -- it's just a matter of adding the model and a few methods.

**Comment by TinaTiel** [comment]
@jonteohr This feature is now available on 1.2.0 if you'd like to check this out. Please note this isn't yet part of a Maven Central Release so you'll need to install the dependency locally.
