### ISSUE TITLE
Centralize Gson config

### ISSUE THREAD

**Issue by TinaTiel** [Twasi/websocket-obs-java#27]
Generally in calls that serialize/deserialize objects, a new Gson instance is being created. [Gson instances are thread-safe](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.0/com/google/gson/Gson.html), so what we can do is initialize GSON in the contructor. 

This would enable us to centralize configuration, for example to add custom serializers/deserializers, or even a [RuntimeTypeAdapter](https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java) to better handle the polymorphism inherent in the Request/Response structure.

This _also_ would enable us to test the serialization/deserialization (or at least smoke-test it) to verify there aren't any mistakes in mapping stuff. Tests would get the Gson instance from OBSCommunicator (or wherever) and verify the configuration is correct.

**Comment by TinaTiel** [comment]
Related to #25

**Comment by ChristopheCVB** [comment]
This can be closed, resolved by #37
