### ISSUE TITLE
Update the library on Maven - README states latest artifactId on MavenCentral is 1.0.5

### ISSUE THREAD

**Issue by rnayabed** [Twasi/websocket-obs-java#28]
The Current one is outdated (1.0.5)

**Comment by TinaTiel** [comment]
There hasn't been an updated release yet on Maven Central
https://search.maven.org/search?q=g:net.twasi

**Comment by rnayabed** [comment]
> There hasn't been an updated release yet on Maven Central
> https://search.maven.org/search?q=g:net.twasi
> 
> If you want to use the latest from Master (until a new release is made @LarsBaertschi @DieserMerlin ) you can run the maven install goal to install it into your local repo for consumption in your projects. This is what I'm doing atm with my own projects since I'm living on the bleeding edge.

Yeah im doing the same right now, but an updated release would be really helpful.

**Comment by DieserMerlin** [comment]
On it, there will be a new release soon

**Comment by rnayabed** [comment]
Thanks a lot!

**Comment by DieserMerlin** [comment]
@LarsBaertschi not only created a new release but also automated the releases so new versions will automatically be on maven itf.

**Comment by rnayabed** [comment]
Awesome!!!!

**Comment by rnayabed** [comment]
@DieserMerlin [Maven](https://mvnrepository.com/artifact/net.twasi/obs-websocket-java) still shows 1.0.5 as the latest version

**Comment by DieserMerlin** [comment]
https://search.maven.org/artifact/net.twasi/obs-websocket-java/1.2.0/jar
