### ISSUE TITLE
Not Usable

### ISSUE THREAD

**Issue by ExtremTechniker** [Twasi/websocket-obs-java#3]
Please push your Repository to the Maven Repository Server to use the code in various projects or if not please make an compiled jar file to use it locally and then make therefor an first release

**Comment by DieserMerlin** [comment]
We have it in our development repository. Just add this repo to your pom:

artifactory.twasi.net

**Comment by LarsBaertschi** [comment]
Hey, thank you for raising this issue. We agree that this is a concern and therfore requested a project on maven central:
https://issues.sonatype.org/browse/OSSRH-54694

We'll let you know as soon as it's available. In the meantime, we have also deployed it to our artifactory instance. You can find it here: https://artifactory.twasi.net/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/net/twasi/obs-websocket-java/1.0.0/obs-websocket-java-1.0.0.jar

You can either link it trough our artifactory, or download the jar and use it locally.

**Comment by LarsBaertschi** [comment]
Our artifact is now available on maven central.

https://mvnrepository.com/artifact/net.twasi/obs-websocket-java/1.0.1
