### ISSUE TITLE
Common Test Resources - SceneCollections, Browser Sources, Images, etc.

### ISSUE THREAD

**Issue by TinaTiel** [Twasi/websocket-obs-java#30]
If we had a common sceneCollection file in the test resources, then we could assert that requests such as getSources etc. return the expected objects. Would be a great first step to containerization-based integration tests

**Comment by TinaTiel** [comment]
Would add this should include the possibility to (manually for now) host a web page for browser source tests; e.g. testing browser source refresh by hitting a page that generates a random number.

**Comment by TinaTiel** [comment]
I've started this on topic-30

**Comment by TinaTiel** [comment]
@LarsBaertschi I've pushed a start onto topic-30, would you mind taking a look and letting me know if the README and initial instructions make sense and work for you?

If all is well, then I'll add a few more tests to exercise the features E2E.

**Comment by LarsBaertschi** [comment]
Hey, I just had a look. I like it, everything is clear to me! It's a very nice way of testing.

**Comment by TinaTiel** [comment]
Awesome, thank you for your feedback! I'll fill it out more and make a PR at some point.
